# FILE: app/services/drafting_service.py
# PHOENIX PROTOCOL - DRAFTING SERVICE V1.2 (SIMPLE API KEY)

import os
import logging
import httpx
from typing import AsyncGenerator, Optional
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

logger = logging.getLogger(__name__)

# Configuration
JURISTI_API_URL = os.environ.get("JURISTI_API_URL", "https://api.juristi.tech")
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
OPENROUTER_MODEL = "deepseek/deepseek-chat"

AI_DISCLAIMER = "\n\n---\n*This document was generated by AI for reference purposes.*"

class DraftingService:
    def __init__(self):
        self.juristi_api_url = JURISTI_API_URL
        
    async def get_legal_context(self, query: str, top_k: int = 5) -> str:
        """Fetch legal context from Juristi's knowledge base"""
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(
                    f"{self.juristi_api_url}/api/v1/legal/public/rag/search",
                    json={"query": query, "top_k": top_k}
                )
                if response.status_code == 200:
                    data = response.json()
                    return data.get("context", "")
                else:
                    logger.error(f"Juristi API error: {response.status_code}")
                    return ""
        except Exception as e:
            logger.error(f"Failed to fetch legal context: {e}")
            return ""
    
    async def draft_document_stream(
        self,
        user_prompt: str,
        document_type: str = "generic",
        include_legal_context: bool = True
    ) -> AsyncGenerator[str, None]:
        """Generate a legal document with optional RAG context from Juristi"""
        
        if not DEEPSEEK_API_KEY:
            yield "Error: AI service not configured."
            yield AI_DISCLAIMER
            return
        
        # Prepare the system prompt
        system_prompt = self._build_system_prompt(document_type)
        
        # Fetch legal context if needed
        legal_context = ""
        if include_legal_context:
            legal_context = await self.get_legal_context(user_prompt)
            logger.info(f"Retrieved legal context length: {len(legal_context)}")
        
        # Build the full prompt
        full_prompt = self._build_full_prompt(user_prompt, legal_context, document_type)
        
        # Call the LLM with streaming
        try:
            # Simple approach - pass API key as string
            llm = ChatOpenAI(
                model=OPENROUTER_MODEL,
                base_url=OPENROUTER_BASE_URL,
                api_key=DEEPSEEK_API_KEY,  # type: ignore
                temperature=0.3,
                streaming=True,
                timeout=120
            )
            
            messages = [
                SystemMessage(content=system_prompt),
                HumanMessage(content=full_prompt)
            ]
            
            async for chunk in llm.astream(messages):
                if chunk.content:
                    yield str(chunk.content)
            
            yield AI_DISCLAIMER
            
        except Exception as e:
            logger.error(f"Draft generation failed: {e}")
            yield f"\n[Error generating document: {str(e)}]"
            yield AI_DISCLAIMER
    
    def _build_system_prompt(self, document_type: str) -> str:
        """Build the system prompt based on document type"""
        base_prompt = """You are a professional legal document assistant. Generate well-structured legal documents in Albanian language.
        
**Formatting Requirements:**
1. Use proper legal document structure with numbered articles or sections
2. Include placeholders in brackets [ ] for client-specific information
3. Use clear, formal language
4. Add a disclaimer that this is a draft and should be reviewed by a legal professional
5. Format with clear headings and paragraphs
"""
        
        type_specific = {
            "generic": "Create a general legal document based on the instructions provided.",
            "employment_contract": "Create an employment contract with standard clauses including: parties, term, compensation, duties, termination, and governing law.",
            "nda": "Create a Non-Disclosure Agreement with confidentiality obligations.",
            "lease_agreement": "Create a commercial or residential lease agreement.",
            "power_of_attorney": "Create a power of attorney document.",
            "padi": "Create a statement of claim (padi) for court proceedings.",
            "pergjigje": "Create a response to a statement of claim (pergjigje).",
            "kunderpadi": "Create a counterclaim (kunderpadi).",
            "ankese": "Create an appeal (ankese).",
            "prapësim": "Create an objection (prapësim).",
        }
        
        instruction = type_specific.get(document_type, type_specific["generic"])
        
        return f"{base_prompt}\n\n**Document Type:** {instruction}"
    
    def _build_full_prompt(self, user_prompt: str, legal_context: str, document_type: str) -> str:
        """Build the full user prompt with legal context"""
        
        context_section = ""
        if legal_context:
            context_section = f"""
## LEGAL REFERENCE (from Kosovo legislation)

{legal_context}

---

"""
        
        return f"""{context_section}
## USER INSTRUCTIONS

{user_prompt}

## OUTPUT

Generate a professional legal document in Albanian language based on the instructions above.
If legal references were provided, incorporate them appropriately.
Use the following structure:
- Title
- Parties (with placeholders)
- Recitals (optional)
- Articles/Sections
- Signatures

Begin your response now:
"""